# @package _global_

algorithm:
  _target_: "gfn_maxent_rl.algos.detailed_balance.GFNDetailedBalance"

  network: ${policy_network}

  target: "periodic"
  target_kwargs:
    update_period: 1000

exp_name_algorithm: "db"
