# @package _global_

algorithm:
  _target_: "gfn_maxent_rl.algos.modified_detailed_balance.ModifiedDetailedBalance"

  network: ${policy_network}

  target: "periodic"
  target_kwargs:
    update_period: 1000

optimizer:
  _target_: "optax.adam"
  learning_rate: ${lr}

exp_name_algorithm: "mdb"
