_target_: "gfn_maxent_rl.algos.soft_qlearning_vanilla.SoftQLearningVanilla"

network:
  _target_: "hydra.utils.get_method"
  path: "gfn_maxent_rl.envs.dag_gfn.policy.q_network"

target: "periodic"
target_kwargs:
  update_period: 1000
